export const supportResourceCatalog = [
  {
    slug: "bd-national-emergency-999",
    name: "National Emergency Service 999",
    description: "For immediate police, fire service, or ambulance assistance in Bangladesh. Use this for imminent danger, physical threats, or an emergency connected to a cyber incident.",
    region: "BANGLADESH",
    serviceType: "EMERGENCY",
    urgency: "IMMEDIATE",
    contactLabel: "Call 999",
    contactValue: "999",
    contactUrl: "tel:999",
    availability: "24/7",
    languages: ["Bangla", "English"],
    eligibility: "Anyone in Bangladesh",
    isOfficial: true,
    sourceUrl: "https://www.police.gov.bd/en/hot_line_number",
  },
  {
    slug: "bd-online-general-diary",
    name: "Bangladesh Police Online GD",
    description: "Submit a police complaint online for eligible incidents, including loss-related matters and other complaints. Cases requiring a criminal case may require an in-person visit.",
    region: "BANGLADESH",
    serviceType: "REPORTING",
    urgency: "TIME_SENSITIVE",
    contactLabel: "Open Online GD",
    contactValue: "gd.police.gov.bd",
    contactUrl: "https://gd.police.gov.bd/",
    availability: "Online service",
    languages: ["Bangla", "English"],
    eligibility: "NID, active mobile number, and live photo are required",
    isOfficial: true,
    sourceUrl: "https://gd.police.gov.bd/",
  },
  {
    slug: "bd-police-cyber-support-women",
    name: "Police Cyber Support for Women",
    description: "Bangladesh Police support for women facing cyber harassment, impersonation, blackmail, account compromise, or non-consensual intimate content. Preserve evidence before reporting.",
    region: "BANGLADESH",
    serviceType: "CYBER_REPORTING",
    urgency: "TIME_SENSITIVE",
    contactLabel: "Call 01320-000888",
    contactValue: "01320-000888",
    contactUrl: "tel:01320000888",
    availability: "Official service; verify current hours before relying on it",
    languages: ["Bangla", "English"],
    eligibility: "Women and girls affected by cybercrime",
    isOfficial: true,
    sourceUrl: "https://www.police.gov.bd/index.php/en/citizen_charter",
  },
  {
    slug: "bd-violence-women-children-109",
    name: "National Helpline Centre 109",
    description: "Support and referral for violence against women and children, including technology-facilitated abuse, sexual exploitation, threats, and child marriage concerns.",
    region: "BANGLADESH",
    serviceType: "PROTECTION",
    urgency: "IMMEDIATE",
    contactLabel: "Call 109",
    contactValue: "109",
    contactUrl: "tel:109",
    availability: "Toll-free, 24 hours",
    languages: ["Bangla"],
    eligibility: "Women, children, families, and witnesses in Bangladesh",
    isOfficial: true,
    sourceUrl: "https://mspvaw.gov.bd/images/contain/pdf/1680564746.pdf",
  },
  {
    slug: "bd-child-helpline-1098",
    name: "Child Helpline 1098",
    description: "Report or seek help for a child at risk, including online grooming, sexual exploitation, cyberbullying, or abuse.",
    region: "BANGLADESH",
    serviceType: "CHILD_SAFETY",
    urgency: "IMMEDIATE",
    contactLabel: "Call 1098",
    contactValue: "1098",
    contactUrl: "tel:1098",
    availability: "Use for urgent child protection concerns",
    languages: ["Bangla"],
    eligibility: "Children, guardians, and concerned adults in Bangladesh",
    isOfficial: true,
    sourceUrl: "https://www.police.gov.bd/en/hot_line_number",
  },
  {
    slug: "bd-government-legal-aid-16430",
    name: "National Legal Aid Services Organization",
    description: "Government legal-aid helpline for people seeking information about legal assistance and referral. It is not a substitute for emergency response.",
    region: "BANGLADESH",
    serviceType: "LEGAL_AID",
    urgency: "GUIDANCE",
    contactLabel: "Call 16430",
    contactValue: "16430",
    contactUrl: "tel:16430",
    availability: "Confirm current service hours with the provider",
    languages: ["Bangla"],
    eligibility: "People seeking legal aid in Bangladesh",
    isOfficial: true,
    sourceUrl: "https://www.police.gov.bd/en/hot_line_number",
  },
  {
    slug: "bd-financial-fraud-response",
    name: "Financial Fraud: Contact Your Provider First",
    description: "For a suspicious card, bank, mobile-financial-service, or account transaction, immediately contact the provider using the number on its official website, app, card, or statement. Ask for a block or dispute and retain the reference number.",
    region: "BANGLADESH",
    serviceType: "FINANCIAL_SAFETY",
    urgency: "IMMEDIATE",
    contactLabel: "Use your provider's official channel",
    contactValue: "Official bank/MFS contact",
    availability: "Act immediately",
    languages: ["Bangla", "English"],
    eligibility: "Customers of affected financial providers",
    isOfficial: true,
    sourceUrl: "https://www.bb.org.bd/",
  },
  {
    slug: "bd-health-helpline-16263",
    name: "Health Helpline 16263",
    description: "Government health-information helpline. Use it to find appropriate health services and seek urgent clinical support after a cyber incident causes severe distress. For an immediate threat to life, call 999 instead.",
    region: "BANGLADESH",
    serviceType: "MENTAL_HEALTH",
    urgency: "TIME_SENSITIVE",
    contactLabel: "Call 16263",
    contactValue: "16263",
    contactUrl: "tel:16263",
    availability: "Government health-information service",
    languages: ["Bangla"],
    eligibility: "People seeking health-service information in Bangladesh",
    isOfficial: true,
    sourceUrl: "https://mefwd.gov.bd/",
  },
  {
    slug: "bd-national-human-rights-16108",
    name: "National Human Rights Helpline",
    description: "Government human-rights support route for reporting or seeking guidance about rights-related concerns. Preserve evidence and use emergency police services first where someone is in immediate danger.",
    region: "BANGLADESH",
    serviceType: "HUMAN_RIGHTS",
    urgency: "GUIDANCE",
    contactLabel: "Call 16108",
    contactValue: "16108",
    contactUrl: "tel:16108",
    availability: "Confirm current service hours with the provider",
    languages: ["Bangla"],
    eligibility: "People seeking human-rights guidance in Bangladesh",
    isOfficial: true,
    sourceUrl: "https://bangladesh.gov.bd/index.php?q=site%2Fview%2Fmservices%2F%E0%A6%95%E0%A6%B2+%E0%A6%B8%E0%A7%87%E0%A6%A8%E0%A7%8D%E0%A6%9F%E0%A6%BE%E0%A6%B0",
  },
  {
    slug: "bd-government-service-333",
    name: "National Information and Service Helpline 333",
    description: "Government information and referral service for public services, social-problem reports, and disaster-assistance requests. It is a referral route, not a replacement for 999 in an emergency.",
    region: "BANGLADESH",
    serviceType: "GOVERNMENT_REFERRAL",
    urgency: "GUIDANCE",
    contactLabel: "Call 333",
    contactValue: "333",
    contactUrl: "tel:333",
    availability: "24/7",
    languages: ["Bangla"],
    eligibility: "Anyone in Bangladesh; callers abroad can use the official overseas number",
    isOfficial: true,
    sourceUrl: "https://333.gov.bd/chat/",
  },
  {
    slug: "global-interpol-cybercrime-guidance",
    name: "INTERPOL Cybercrime Information",
    description: "International cybercrime information and law-enforcement coordination context. Individuals should report a crime to their local police; INTERPOL does not take individual crime reports directly.",
    region: "INTERNATIONAL",
    serviceType: "INTERNATIONAL_REPORTING",
    urgency: "GUIDANCE",
    contactLabel: "Visit INTERPOL guidance",
    contactValue: "interpol.int",
    contactUrl: "https://www.interpol.int/Crimes/Cybercrime",
    availability: "Information resource",
    languages: ["English"],
    eligibility: "Global public guidance",
    isOfficial: true,
    sourceUrl: "https://www.interpol.int/Crimes/Cybercrime",
  },
  {
    slug: "global-stopncii",
    name: "StopNCII.org",
    description: "A tool for adults concerned that intimate images may be shared without consent. It creates a hash on the device to help participating platforms detect matching images; it is not a police report or a guarantee of removal everywhere.",
    region: "INTERNATIONAL",
    serviceType: "IMAGE_ABUSE",
    urgency: "TIME_SENSITIVE",
    contactLabel: "Open StopNCII",
    contactValue: "stopncii.org",
    contactUrl: "https://stopncii.org/",
    availability: "Online service",
    languages: ["English"],
    eligibility: "Adults concerned about non-consensual intimate-image sharing",
    isOfficial: true,
    sourceUrl: "https://stopncii.org/",
  },
  {
    slug: "global-iwf-report",
    name: "Internet Watch Foundation Reporting Portal",
    description: "Report suspected child sexual abuse imagery encountered online. Do not download, forward, or save illegal content; report the URL or location where it was found.",
    region: "INTERNATIONAL",
    serviceType: "CHILD_SAFETY",
    urgency: "IMMEDIATE",
    contactLabel: "Make a report",
    contactValue: "iwf.org.uk",
    contactUrl: "https://www.iwf.org.uk/en/uk-report/",
    availability: "Online reporting",
    languages: ["English"],
    eligibility: "Global reporting guidance; local law enforcement may also be needed",
    isOfficial: true,
    sourceUrl: "https://www.iwf.org.uk/",
  },
  {
    slug: "ethical-hacker-authorized-security-help",
    name: "Ethical Hacker / Incident Response Specialist",
    description: "For an organization or account owner who needs authorized technical incident response: contain access, preserve logs, assess exposure, and recover safely. Use only a vetted professional with written authorization and a defined scope. Never hire anyone promising to hack, recover, or retaliate against another person's account.",
    region: "INTERNATIONAL",
    serviceType: "ETHICAL_HACKER",
    urgency: "TIME_SENSITIVE",
    contactLabel: "Learn about responsible vulnerability disclosure",
    contactValue: "cisa.gov",
    contactUrl: "https://www.cisa.gov/vulnerability-disclosure-policy-template",
    availability: "Guidance for authorized security work",
    languages: ["English"],
    eligibility: "System owners and organizations with explicit authorization",
    isOfficial: true,
    sourceUrl: "https://www.cisa.gov/topics/cyber-threats-and-advisories/vulnerability-disclosure-policy",
  },
];
