ALTER TABLE "CrimeType" ADD COLUMN "subtypes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "CrimeType" ADD COLUMN "immediateSteps" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "CrimeType" ADD COLUMN "evidenceChecklist" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
