import { LawCategory, LawRegion, LawStatus } from "../../generated/prisma/enums.ts";

export const lawCatalog = [
  {
    slug: "bangladesh-cyber-security-act-2026",
    title: "Cyber Security Act, 2026",
    description: "Bangladesh's current core cyber-security statute. Use it as the starting point for unlawful access, interference with systems or data, online offences, and cyber-incident response. Confirm the applicable section and current text before giving case-specific advice.",
    region: LawRegion.BANGLADESH,
    category: LawCategory.CYBERCRIME,
    authority: "Information and Communication Technology Division, Government of Bangladesh",
    publishedDate: "2026",
    status: LawStatus.IN_FORCE,
    legalTopics: ["unauthorised access", "system interference", "digital offences", "incident response"],
    applicability: ["account takeover", "hacking", "malware", "data interference", "online abuse"],
    source: "https://ictd.gov.bd/pages/laws",
  },
  {
    slug: "bangladesh-personal-data-protection-act-2026",
    title: "Personal Data Protection Act, 2026",
    description: "Bangladesh's current personal-data framework. Relevant to unlawful collection, use, disclosure, retention, and security of personal data by organisations and digital services.",
    region: LawRegion.BANGLADESH,
    category: LawCategory.DATA_PROTECTION,
    authority: "Information and Communication Technology Division, Government of Bangladesh",
    publishedDate: "2026",
    status: LawStatus.IN_FORCE,
    legalTopics: ["personal data", "consent", "data security", "data disclosure"],
    applicability: ["doxxing", "data breach", "identity misuse", "privacy violation"],
    source: "https://ictd.gov.bd/pages/laws",
  },
  {
    slug: "bangladesh-national-data-management-act-2026",
    title: "National Data Management Act, 2026",
    description: "Framework for national data management and governance. Relevant where a case concerns public-sector data, data stewardship, interoperability, or government-held information.",
    region: LawRegion.BANGLADESH,
    category: LawCategory.DATA_PROTECTION,
    authority: "Information and Communication Technology Division, Government of Bangladesh",
    publishedDate: "2026",
    status: LawStatus.IN_FORCE,
    legalTopics: ["national data", "data governance", "public-sector data"],
    applicability: ["government data exposure", "public database misuse"],
    source: "https://ictd.gov.bd/pages/laws",
  },
  {
    slug: "bangladesh-ict-act-2006",
    title: "Information and Communication Technology Act, 2006",
    description: "Establishes foundational rules for electronic records, electronic signatures, certification, and ICT-related offences. It remains a key reference for legal recognition of digital transactions and records.",
    region: LawRegion.BANGLADESH,
    category: LawCategory.CYBERCRIME,
    authority: "Government of Bangladesh",
    publishedDate: "2006, amended 2009 and 2013",
    status: LawStatus.IN_FORCE,
    legalTopics: ["electronic records", "electronic signatures", "digital certification"],
    applicability: ["digital contract", "electronic signature", "online transaction"],
    source: "https://ncsa.gov.bd/site/page/50cf7d8c-954c-413f-8f23-eee744a1cd8d/Acts-%26-Rules",
  },
  {
    slug: "bangladesh-telecommunication-regulation-act-2001",
    title: "Bangladesh Telecommunication Regulation Act, 2001",
    description: "Telecommunications regulatory framework relevant to network and service-provider conduct, communications infrastructure, and regulatory complaints.",
    region: LawRegion.BANGLADESH,
    category: LawCategory.TELECOMMUNICATIONS,
    authority: "Bangladesh Telecommunication Regulatory Commission",
    publishedDate: "2001",
    status: LawStatus.IN_FORCE,
    legalTopics: ["telecommunications", "network services", "service providers"],
    applicability: ["SIM misuse", "telecom complaint", "network abuse"],
    source: "https://old.bdlaws.minlaw.gov.bd/bangladesh-code-alphabetical-index.html",
  },
  {
    slug: "bangladesh-evidence-act-1872-amended-2022",
    title: "Evidence Act, 1872, as amended by the Evidence (Amendment) Act, 2022",
    description: "Provides the evidentiary basis for digital and electronic records, including provisions concerning proof of digital records. Essential for preserving screenshots, device records, logs, and other evidence.",
    region: LawRegion.BANGLADESH,
    category: LawCategory.ELECTRONIC_EVIDENCE,
    authority: "Ministry of Law, Justice and Parliamentary Affairs",
    publishedDate: "1872; digital-record amendments 2022",
    status: LawStatus.IN_FORCE,
    legalTopics: ["digital evidence", "electronic records", "proof"],
    applicability: ["all cybercrime reports", "evidence preservation", "court proceedings"],
    source: "https://bdlaws.minlaw.gov.bd/act-print-1416.html",
  },
  {
    slug: "bangladesh-pornography-control-act-2012",
    title: "Pornography Control Act, 2012",
    description: "Addresses pornography-related conduct and materials. It is relevant to non-consensual intimate imagery, sexually explicit digital content, and related exploitation, subject to the exact statutory elements.",
    region: LawRegion.BANGLADESH,
    category: LawCategory.CHILD_PROTECTION,
    authority: "Ministry of Home Affairs, Government of Bangladesh",
    publishedDate: "2012",
    status: LawStatus.IN_FORCE,
    legalTopics: ["intimate imagery", "sexual content", "digital exploitation"],
    applicability: ["revenge porn", "non-consensual intimate imagery", "child sexual content"],
    source: "https://moha.gov.bd/pages/laws/%E0%A6%AA%E0%A6%B0%E0%A7%8D%E0%A6%A8%E0%A7%8B%E0%A6%97%E0%A7%8D%E0%A6%B0%E0%A6%BE%E0%A6%AB%E0%A6%BF-%E0%A6%A8%E0%A6%BF%E0%A7%9F%E0%A6%A8%E0%A7%8D%E0%A6%A4%E0%A7%8D%E0%A6%B0%E0%A6%A3-%E0%A6%86%E0%A6%87%E0%A6%A8-%E0%A7%A8%E0%A7%A6%E0%A7%A7%E0%A7%A8-%E0%A7%A8%E0%A7%A6%E0%A7%A7%E0%A7%A8-%E0%A6%B8%E0%A6%A8%E0%A7%87%E0%A6%B0-%E0%A7%AF%E0%A6%A8%E0%A6%82-%E0%A6%86%E0%A6%87%E0%A6%A8-b50b95-6940319935ce18e1c0553063",
  },
  {
    slug: "bangladesh-penal-code-1860",
    title: "Penal Code, 1860",
    description: "General criminal-law provisions can apply where technology is the medium, including cheating, criminal intimidation, defamation, extortion, forgery, and offences against property or persons.",
    region: LawRegion.BANGLADESH,
    category: LawCategory.CYBERCRIME,
    authority: "Ministry of Law, Justice and Parliamentary Affairs",
    publishedDate: "1860",
    status: LawStatus.IN_FORCE,
    legalTopics: ["cheating", "intimidation", "extortion", "defamation", "forgery"],
    applicability: ["online threats", "fraud", "blackmail", "impersonation", "defamation"],
    source: "https://old.bdlaws.minlaw.gov.bd/bangladesh-code-alphabetical-index.html",
  },
  {
    slug: "bangladesh-human-trafficking-act-2012",
    title: "Prevention and Suppression of Human Trafficking Act, 2012",
    description: "Relevant where online platforms, recruitment, coercion, exploitation, or digital communications facilitate trafficking or sexual exploitation.",
    region: LawRegion.BANGLADESH,
    category: LawCategory.CHILD_PROTECTION,
    authority: "Government of Bangladesh",
    publishedDate: "2012",
    status: LawStatus.IN_FORCE,
    legalTopics: ["trafficking", "online recruitment", "exploitation"],
    applicability: ["online grooming", "coercion", "trafficking recruitment"],
    source: "https://bangladesh.gov.bd/sites/default/files/files/bangladesh.gov.bd/gurd_file_new/4240d402_e5b9_4afa_87fa_2ef9c7f4635a/%E0%A6%AA%E0%A6%BE%E0%A6%9A%E0%A6%BE%E0%A6%B0%20%E0%A6%AA%E0%A7%8D%E0%A6%B0%E0%A6%A4%E0%A6%BF%E0%A6%B0%E0%A7%8B%E0%A6%A7%20%E0%A6%93%20%E0%A6%A6%E0%A6%AE%E0%A6%A8%20%E0%A6%86%E0%A6%87%E0%A6%A8-%E0%A7%A8%E0%A7%A6%E0%A7%A7%E0%A7%A8.pdf",
  },
  {
    slug: "bangladesh-money-laundering-prevention-act-2012",
    title: "Money Laundering Prevention Act, 2012",
    description: "Supports investigations involving proceeds of crime and financial flows. It may be relevant to organised online fraud, mule accounts, and laundering of cybercrime proceeds.",
    region: LawRegion.BANGLADESH,
    category: LawCategory.FINANCIAL,
    authority: "Government of Bangladesh and Bangladesh Financial Intelligence Unit",
    publishedDate: "2012",
    status: LawStatus.IN_FORCE,
    legalTopics: ["money laundering", "proceeds of crime", "financial intelligence"],
    applicability: ["online fraud", "mule account", "financial scam"],
    source: "https://old.bdlaws.minlaw.gov.bd/bangladesh-code-chronological-index.html",
  },
  {
    slug: "budapest-convention-cybercrime",
    title: "Convention on Cybercrime (Budapest Convention, ETS No. 185)",
    description: "International framework for criminalising cyber offences, securing electronic evidence, and cooperation between participating States. It is a reference for cross-border cases and domestic legislative design.",
    region: LawRegion.INTERNATIONAL,
    category: LawCategory.INTERNATIONAL_COOPERATION,
    authority: "Council of Europe",
    publishedDate: "2001; in force 2004",
    status: LawStatus.REFERENCE,
    legalTopics: ["cybercrime", "electronic evidence", "international cooperation"],
    applicability: ["cross-border investigation", "electronic evidence", "international cooperation"],
    source: "https://www.coe.int/en/web/cybercrime/convention-on-cybercrime",
  },
  {
    slug: "budapest-convention-second-additional-protocol",
    title: "Second Additional Protocol to the Budapest Convention (CETS No. 224)",
    description: "Provides enhanced cooperation and disclosure mechanisms for electronic evidence. It is a reference framework for cross-border preservation and disclosure requests.",
    region: LawRegion.INTERNATIONAL,
    category: LawCategory.ELECTRONIC_EVIDENCE,
    authority: "Council of Europe",
    publishedDate: "2021",
    status: LawStatus.REFERENCE,
    legalTopics: ["cross-border evidence", "service provider cooperation", "data disclosure"],
    applicability: ["foreign platform evidence", "cross-border investigation"],
    source: "https://www.coe.int/en/web/cybercrime/convention-on-cybercrime",
  },
  {
    slug: "un-convention-against-cybercrime-2024",
    title: "United Nations Convention against Cybercrime",
    description: "UN treaty on cooperation against specified ICT-enabled crime and sharing electronic evidence. Its status must be checked before relying on it in a jurisdiction-specific matter.",
    region: LawRegion.INTERNATIONAL,
    category: LawCategory.INTERNATIONAL_COOPERATION,
    authority: "United Nations",
    publishedDate: "2024",
    status: LawStatus.NOT_IN_FORCE,
    legalTopics: ["international cooperation", "electronic evidence", "ICT-enabled crime"],
    applicability: ["cross-border investigation", "future treaty framework"],
    source: "https://treaties.un.org/Pages/ViewDetails.aspx?chapter=18&mtdsg_no=XVIII-16&src=TREATY",
  },
  {
    slug: "general-data-protection-regulation",
    title: "General Data Protection Regulation (EU) 2016/679",
    description: "EU data-protection regulation governing personal-data processing. It can apply extraterritorially in defined circumstances, including certain services offered to people in the EU.",
    region: LawRegion.INTERNATIONAL,
    category: LawCategory.DATA_PROTECTION,
    authority: "European Union",
    publishedDate: "2016; applicable 2018",
    status: LawStatus.IN_FORCE,
    legalTopics: ["personal data", "privacy", "data controller", "data breach"],
    applicability: ["EU-facing service", "data breach", "privacy compliance"],
    source: "https://eur-lex.europa.eu/legal-content/EN/LSU/?uri=celex%3A32016R0679",
  },
  {
    slug: "iccp-r-article-17",
    title: "International Covenant on Civil and Political Rights (Article 17)",
    description: "International human-rights protection against arbitrary or unlawful interference with privacy, family, home, correspondence, honour, and reputation. It informs privacy and safeguards analysis.",
    region: LawRegion.INTERNATIONAL,
    category: LawCategory.DATA_PROTECTION,
    authority: "United Nations",
    publishedDate: "1966; in force 1976",
    status: LawStatus.REFERENCE,
    legalTopics: ["privacy", "correspondence", "reputation", "human rights"],
    applicability: ["privacy violation", "digital surveillance", "online reputation"],
    source: "https://www.ohchr.org/sites/default/files/Documents/ProfessionalInterest/ccpr.pdf",
  },
];
